//current as of 5/8/2023 1 pm
export const dummyDb = {
  events: [
    {
      date: '2023-06-01',
      endtime: '18:00',
      host_id: 1,
      id: 1,
      location: '123 Main St.',
      name: "John and Jane's Wedding",
      starttime: '13:00',
    },
    {
      date: '2023-07-15',
      endtime: '23:00',
      host_id: 3,
      id: 2,
      location: '456 Oak St.',
      name: "Bob's Wedding",
      starttime: '19:00',
    },
  ],
  guest_tags: [
    {
      guest_id: 1,
      id: 1,
      tag_id: 1,
    },
    {
      guest_id: 2,
      id: 2,
      tag_id: 2,
    },
    {
      guest_id: 2,
      id: 3,
      tag_id: 3,
    },
    {
      guest_id: 3,
      id: 4,
      tag_id: 3,
    },
  ],
  guestlist: [
    {
      event_id: 1,
      guest_id: 2,
      id: 1,
      role: 'Host',
      tag_id: 1,
    },
    {
      arrival_time: '2022-07-31T18:00:00Z',
      departure_time: '2022-08-02T12:00:00Z',
      event_id: 1,
      flight_number: 'UA123',
      guest_id: 3,
      id: 2,
      role: 'Host',
      tag_id: 2,
    },
    {
      event_id: 2,
      guest_id: 1,
      id: 3,
      role: 'Guest',
      tag_id: 1,
    },
    {
      event_id: 2,
      guest_id: 2,
      id: 4,
      role: 'Guest',
      tag_id: 2,
    },
  ],
  messageboard: [
    {
      created_at: '2022-06-01T12:00:00Z',
      event_id: 1,
      id: 1,
      message: 'Excited for the wedding!',
      updated_at: '2022-06-01T12:00:00Z',
      user_id: 2,
    },
    {
      created_at: '2022-06-02T10:30:00Z',
      event_id: 1,
      id: 2,
      message: "Me too! Can't wait to see everyone!",
      updated_at: '2022-06-02T10:30:00Z',
      user_id: 3,
    },
    {
      created_at: '2022-07-01T09:15:00Z',
      event_id: 2,
      id: 3,
      message: 'Had a great time at the wedding last night!',
      updated_at: '2022-07-01T09:15:00Z',
      user_id: 1,
    },
  ],
  notification_recipients: [
    {
      guest_id: 1,
      id: 1,
      notification_id: 1,
    },
    {
      guest_id: 2,
      id: 2,
      notification_id: 1,
    },
    {
      guest_id: 1,
      id: 3,
      notification_id: 2,
      tag_id: 1,
    },
    {
      id: 4,
      notification_id: 2,
      tag_id: 2,
    },
    {
      id: 5,
      notification_id: 3,
      tag_id: 3,
    },
  ],
  notifications: [
    {
      body: 'The wedding ceremony will start in 30 minutes!',
      event_id: 1,
      id: 1,
      scheduled_time: '2022-08-01T19:30:00Z',
      title: 'Reminder: Wedding Ceremony',
    },
    {
      body: 'The wedding reception will start in 1 hour!',
      event_id: 1,
      id: 2,
      scheduled_time: '2022-08-01T20:00:00Z',
      title: 'Reminder: Wedding Reception',
    },
    {
      body: 'The birthday party will start in 2 hours!',
      event_id: 2,
      id: 3,
      scheduled_time: '2022-09-01T18:00:00Z',
      title: 'Reminder: Birthday Party',
    },
  ],
  subevents: [
    {
      date: '2022-06-10',
      end_time: '22:00:00',
      event_id: 1,
      id: 1,
      location: '123 Main St',
      name: 'Rehearsal Dinner',
      start_time: '18:00:00',
      tag_id: 1,
    },
    {
      date: '2022-06-11',
      end_time: '12:00:00',
      event_id: 1,
      id: 2,
      location: '456 Oak Ave',
      name: 'Morning Brunch',
      start_time: '10:00:00',
      tag_id: 2,
    },
    {
      date: '2022-08-01',
      end_time: '21:30:00',
      event_id: 2,
      id: 3,
      location: '789 Maple St',
      name: 'Welcome Dinner',
      start_time: '18:30:00',
      tag_id: 0,
    },
  ],
  tags: [
    {
      id: 1,
      name: 'VIP',
    },
    {
      id: 2,
      name: 'Family',
    },
    {
      id: 3,
      name: 'Friend',
    },
  ],
  users: [
    {
      email: 'johndoe@example.com',
      firstname: 'John',
      id: 1,
      lastname: 'Doe',
      password: 'password123',
    },
    {
      email: 'janedoe@example.com',
      firstname: 'Jane',
      id: 2,
      lastname: 'Doe',
      password: 'password456',
    },
    {
      email: 'bobsmith@example.com',
      firstname: 'Bob',
      id: 3,
      lastname: 'Smith',
      password: 'password789',
    },
  ],
};
